name: Terraform AWS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform (Ensure Backend is Configured)
        run: terraform init -backend-config="bucket=bharghav-terraform-state" \
                            -backend-config="key=terraform.tfstate" \
                            -backend-config="region=us-east-1" \
                            -backend-config="dynamodb_table=terraform-lock"

      - name: Auto-format Terraform Code
        run: terraform fmt -recursive

      - name: Validate Terraform Code
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Apply Terraform Changes (Manual Approval Required)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
